name: Question
description: Ask a question about palladium.
labels: [question]
assignees: ITsMrToad
body:
  - type: textarea
    attributes:
      label: Question
    validations:
      required: true
